//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string Year { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string UserId { get; set; }
        public string AcademicStatus { get; set; }
        public string PreviousClass { get; set; }
        public string NewClass { get; set; }
        public int SessionId { get; set; }
    }
}
