//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermlyResult
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> SubjectTeacherId { get; set; }
        public Nullable<float> AssignScore1 { get; set; }
        public Nullable<float> AssignScore2 { get; set; }
        public Nullable<float> AssignScore3 { get; set; }
        public Nullable<float> AssignScore4 { get; set; }
        public Nullable<float> TestScore1 { get; set; }
        public Nullable<float> TestScore2 { get; set; }
        public Nullable<float> TestScore3 { get; set; }
        public Nullable<float> TestScore4 { get; set; }
        public Nullable<float> ExamScore { get; set; }
        public Nullable<float> Total { get; set; }
        public string Grade { get; set; }
        public Nullable<float> AverageScore { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> ArmId { get; set; }
        public string Remarks { get; set; }
        public byte[] CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
